### ISSUE TITLE
Timestamps broken

### ISSUE THREAD

**Issue by eevleevs** [johansatge/workflowy-php#7] opened 2018-11-11 03:29 UTC
Hi, I am getting weird timestamps from $list->getLastModifiedTime() (new items in 2356), and nothing from $list->getCompletedTime(). Please check.

**Comment by johansatge** [comment] 2018-11-11 15:10
Hi! thanks for reporting this.

It looks like WorkFlowy has updated the timestamps format in its internal API. I have updated mine to take that into account. The functions should be fixed if you update to `0.2.1`.

Let me know if you still reproduce the issue! thx.

**Closed as completed by johansatge** 2018-11-11 15:10 UTC

**Comment by eevleevs** [comment] 2018-11-11 15:31
Working here, thanks!
